apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ui-app
spec:
  replicas: 2  # Number of instances of the app 
  selector:
    matchLabels:
      app: flask-ui-app
  template:
    metadata:
      labels:
        app: flask-ui-app
    spec:
      containers:
      - name: flask-ui-container
        image: flask-ui-app:latest  
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-ui-service
spec:
  selector:
    app: flask-ui-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  
